/**
 * Created by lei_sun on 2019/6/6.
 */
export const GET_APIOPEN_VIDEO_RECOMMEND = 'GET_APIOPEN_VIDEO_RECOMMEND';
export const GET_APIOPEN_VIDEO_RECOMMEND_SUCCEEDED = 'GET_APIOPEN_VIDEO_RECOMMEND_SUCCEEDED';
export const GET_APIOPEN_VIDEO_RECOMMEND_FAILED = 'GET_APIOPEN_VIDEO_RECOMMEND_FAILED';