/**
 * Created by lei_sun on 2019/6/6.
 */
export const GET_MATH_QUIZ = 'GET_MATH_QUIZ';
export const GET_MATH_QUIZ_SUCCEEDED = 'GET_MATH_QUIZ_SUCCEEDED';
export const GET_MATH_QUIZ_FAILED = 'GET_MATH_QUIZ_FAILED';

export const GET_MATH_QUIZ_ITEMS = 'GET_MATH_QUIZ_ITEMS';
export const GET_MATH_QUIZ_ITEMS_SUCCEEDED = 'GET_MATH_QUIZ_ITEMS_SUCCEEDED';
export const GET_MATH_QUIZ_ITEMS_FAILED = 'GET_MATH_QUIZ_ITEMS_FAILED';

export const SET_MATH_QUIZ_ITEMS = 'SET_MATH_QUIZ_ITEMS';
export const SET_MATH_QUIZ_ITEMS_SUCCEEDED = 'SET_MATH_QUIZ_ITEMS_SUCCEEDED';
export const SET_MATH_QUIZ_ITEMS_FAILED = 'SET_MATH_QUIZ_ITEMS_FAILED';