"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.GET_GITHUB_ZEIT_NEXT_FAILED = exports.GET_GITHUB_ZEIT_NEXT_SUCCEEDED = exports.GET_GITHUB_ZEIT_NEXT = void 0;

/**
 * Created by lei_sun on 2019/6/6.
 */
var GET_GITHUB_ZEIT_NEXT = 'GET_GITHUB_ZEIT_NEXT';
exports.GET_GITHUB_ZEIT_NEXT = GET_GITHUB_ZEIT_NEXT;
var GET_GITHUB_ZEIT_NEXT_SUCCEEDED = 'GET_GITHUB_ZEIT_NEXT_SUCCEEDED';
exports.GET_GITHUB_ZEIT_NEXT_SUCCEEDED = GET_GITHUB_ZEIT_NEXT_SUCCEEDED;
var GET_GITHUB_ZEIT_NEXT_FAILED = 'GET_GITHUB_ZEIT_NEXT_FAILED';
exports.GET_GITHUB_ZEIT_NEXT_FAILED = GET_GITHUB_ZEIT_NEXT_FAILED;