/**
 * Created by lei_sun on 2019/6/6.
 */
export const GET_GITHUB_ZEIT_NEXT = 'GET_GITHUB_ZEIT_NEXT';
export const GET_GITHUB_ZEIT_NEXT_SUCCEEDED = 'GET_GITHUB_ZEIT_NEXT_SUCCEEDED';
export const GET_GITHUB_ZEIT_NEXT_FAILED = 'GET_GITHUB_ZEIT_NEXT_FAILED';