'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/**
 * Created by lei_sun on 2019/6/6.
 */
var GET_APIOPEN_VIDEO_RECOMMEND = exports.GET_APIOPEN_VIDEO_RECOMMEND = 'GET_APIOPEN_VIDEO_RECOMMEND';
var GET_APIOPEN_VIDEO_RECOMMEND_SUCCEEDED = exports.GET_APIOPEN_VIDEO_RECOMMEND_SUCCEEDED = 'GET_APIOPEN_VIDEO_RECOMMEND_SUCCEEDED';
var GET_APIOPEN_VIDEO_RECOMMEND_FAILED = exports.GET_APIOPEN_VIDEO_RECOMMEND_FAILED = 'GET_APIOPEN_VIDEO_RECOMMEND_FAILED';