'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/**
 * Created by lei_sun on 2019/6/6.
 */
var GET_MATH_QUIZ = exports.GET_MATH_QUIZ = 'GET_MATH_QUIZ';
var GET_MATH_QUIZ_SUCCEEDED = exports.GET_MATH_QUIZ_SUCCEEDED = 'GET_MATH_QUIZ_SUCCEEDED';
var GET_MATH_QUIZ_FAILED = exports.GET_MATH_QUIZ_FAILED = 'GET_MATH_QUIZ_FAILED';

var GET_MATH_QUIZ_ITEMS = exports.GET_MATH_QUIZ_ITEMS = 'GET_MATH_QUIZ_ITEMS';
var GET_MATH_QUIZ_ITEMS_SUCCEEDED = exports.GET_MATH_QUIZ_ITEMS_SUCCEEDED = 'GET_MATH_QUIZ_ITEMS_SUCCEEDED';
var GET_MATH_QUIZ_ITEMS_FAILED = exports.GET_MATH_QUIZ_ITEMS_FAILED = 'GET_MATH_QUIZ_ITEMS_FAILED';

var SET_MATH_QUIZ_ITEMS = exports.SET_MATH_QUIZ_ITEMS = 'SET_MATH_QUIZ_ITEMS';
var SET_MATH_QUIZ_ITEMS_SUCCEEDED = exports.SET_MATH_QUIZ_ITEMS_SUCCEEDED = 'SET_MATH_QUIZ_ITEMS_SUCCEEDED';
var SET_MATH_QUIZ_ITEMS_FAILED = exports.SET_MATH_QUIZ_ITEMS_FAILED = 'SET_MATH_QUIZ_ITEMS_FAILED';